# Generated by Django 5.2.7 on 2025-10-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='seat_set',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
