# Generated by Django 5.2.7 on 2025-10-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_user_movie_seat_set_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seat_set',
        ),
    ]
