# Generated by Django 5.2.7 on 2025-10-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_movie_seat_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='seat_set',
            field=models.ManyToManyField(to='bookings.seat'),
        ),
    ]
