# Generated by Django 5.2.7 on 2025-10-07 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_movie_seat_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='seat_set',
        ),
        migrations.AddField(
            model_name='movie',
            name='seat_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.seat'),
            preserve_default=False,
        ),
    ]
