# Generated by Django 5.2.7 on 2025-10-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_movie_seat_set_movie_seat_set'),
        ('bookings', '0006_seed_initial_data'),
    ]

    operations = [
    ]
